name: festeasy
description: Migracion de Festeasy App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  equatable: ^2.0.5
  go_router: ^17.0.0
  provider: ^6.1.2
  dartz: ^0.10.1
  supabase_flutter: ^2.10.3

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
  flutter_launcher_icons: "^0.13.1" # Added for launcher icons

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/ # Declare assets folder

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # set min Android SDK min_sdk_android
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"
